#!/bin/bash

 # Color
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'


echo "$YELLOW Processing..."
 # Here you define the absolute path of your script
 scriptPath="./script"

NEXT="next"
TURBO="turbo"
NODE_MODULES="node-modules"
LOCK="lock"

 # Here you execute your script
source $scriptPath/$NEXT
echo "$GREEN- Executing: $NEXT.sh => $BLUE .next folders removed"

source $scriptPath/$LOCK
echo "$GREEN- Executing: $LOCK.sh => $BLUE pnpm-lock.yaml folders removed"

# source $scriptPath/$TURBO
# echo "$GREEN- Executing: $TURBO.sh"
source $scriptPath/$NODE_MODULES
echo "$GREEN- Executing: $NODE_MODULES.sh => $BLUE node_modules folders removed"

echo "$PURPLE Done"

 # Result of script execution

 result=$?